<?php
/**
 * Implements hook_deploy_add_to_plan().
 */
function auto_deploy_menu_item_deploy_add_to_plan($deploy_plan, $entity_type, $entity) {
  if ($entity_type != 'node') {
    return;
  }
  // Prepare the node for the edit form so that $node->menu always exists.
  $menu_name = strtok(variable_get('menu_parent_' . $entity->type, 'main-menu:0'), ':');
  if (isset($entity->nid)) {
    $mlid = FALSE;
    // Give priority to the default menu
    $type_menus = variable_get('menu_options_' . $entity->type, array('main-menu' => 'main-menu'));
    if (in_array($menu_name, $type_menus)) {
      $mlid = db_query_range("SELECT mlid FROM {menu_links} WHERE link_path = :path AND menu_name = :menu_name AND module = 'menu' ORDER BY mlid ASC", 0, 1, array(
        ':path' => 'node/' . $entity->nid,
        ':menu_name' => $menu_name,
      ))->fetchField();
    }
    // Check all allowed menus if a link does not exist in the default menu.
    if (!$mlid && !empty($type_menus)) {
      $mlid = db_query_range("SELECT mlid FROM {menu_links} WHERE link_path = :path AND module = 'menu' AND menu_name IN (:type_menus) ORDER BY mlid ASC", 0, 1, array(
        ':path' => 'node/' . $entity->nid,
        ':type_menus' => array_values($type_menus),
      ))->fetchField();
    }
    if ($mlid) {
      $entity = entity_load_single('menu_link', $mlid);
      deploy_manager_add_to_plan($deploy_plan, 'menu_link', $entity);
    }
  }
}
